port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - stun.*.*.*
    - stun.*.*
    - miwifi.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - netis.cc
    - router.asus.com
    - repeater.asus.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - tplinkrepeater.net
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  default-nameserver:
    - 9.9.9.9
  nameserver:
    - 1.2.4.8
    - 210.2.4.8
    - 223.5.5.5
    - 223.6.6.6
    - 52.80.52.52
    - 117.50.10.10
    - 180.76.76.76
    - 119.28.28.28
    - 119.29.29.29
    - 114.114.114.114
    - 114.114.115.115
    - 101.226.4.6
    - 218.30.118.6
    - 123.125.81.6
    - 140.207.198.6
    - 202.38.64.1
    - 202.112.20.131
    - 202.141.160.95
    - 202.141.160.99
    - 202.141.176.95
    - 202.141.176.99
    - tls://dot.pub:853
    - tls://1.12.12.12:853
    - tls://120.53.53.53:853
    - https://doh.pub/dns-query
    - https://sm2.doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://dns.rubyfish.cn/dns-query
  fallback:
    - 9.9.9.9
    - 149.112.112.112
    - 8.8.4.4
    - 8.8.8.8
    - 1.0.0.1
    - 1.1.1.1
    - 208.67.220.220
    - 208.67.220.222
    - 208.67.222.220
    - 208.67.222.222
    - 195.46.39.39
    - 195.46.39.40
    - 168.95.1.1
    - 203.80.96.10
    - 168.95.192.1
    - 164.124.101.2
    - 164.124.107.9
    - 203.248.252.2
    - 203.248.242.2
    - 80.80.80.80
    - 80.80.81.81
    - 199.85.126.10
    - 199.85.127.10
    - 168.126.63.1
    - 168.126.63.2
    - 139.175.252.16
    - 139.175.55.244
    - 202.45.84.58
    - 202.45.84.59
    - 8.26.56.26
    - 23.253.163.53
    - 77.88.8.1
    - 77.88.8.8
    - 89.233.43.71
    - 91.239.100.100
    - 198.101.242.72
    - 8.20.247.20
    - 64.6.64.6
    - 64.6.65.6
    - 209.244.0.3
    - 209.244.0.4
    - 210.220.163.82
    - 219.250.36.130
    - 202.14.67.4
    - 84.200.69.80
    - 84.200.70.40
    - 202.14.67.14
    - 156.154.70.1
    - 156.154.71.1
    - 216.146.35.35
    - 216.146.36.36
    - 77.109.148.136
    - 77.109.148.137
    - 101.101.101.101
    - 101.102.103.104
    - 74.82.42.42
    - 66.220.18.42
    - https://dns.quad9.net/dns-query
    - https://dns9.quad9.net/dns-query
    - tls://dns.google:853
    - https://8.8.4.4/dns-query
    - https://8.8.8.8/dns-query
    - https://dns.google/dns-query
    - tls://1.0.0.1:853
    - tls://1.1.1.1:853
    - tls://one.one.one.one
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.daycat.space/dns-query
    - https://dns.adguard.com/dns-query
    - https://dns-family.adguard.com/dns-query
    - https://dns-unfiltered.adguard.com/dns-query
    - tls://b.iqiq.io:853
    - tls://h.iqiq.io:853
    - tls://j.iqiq.io:853
    - tls://c.passcloud.xyz:853
    - tls://x.passcloud.xyz:853
    - https://a.passcloud.xyz/hk
    - https://a.passcloud.xyz/am
    - https://a.passcloud.xyz/us
    - https://a.passcloud.xyz/sz
    - https://a.passcloud.xyz/cdn
    - https://a.passcloud.xyz/dns-query
    - https://worldwide.passcloud.xyz/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - 其他国家
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 手动选择
    type: select
    proxies:
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - 其他国家
      - REJECT
      - DIRECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 全球媒体
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 国内媒体
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 自动选择
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 失败切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:

rule-providers: # rule-providers from Logyalsoldier/clash-rules and blackmatrix7/ios_rule_script
  Applications:
    type: http
    behavior: classical # https://github.com/Dreamacro/clash/issues/1165
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/TopFreeProxies/applications.txt
  Apple:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/TopFreeProxies/apple.txt
  iCloud:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/TopFreeProxies/icloud.txt
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/TopFreeProxies/microsoft.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
    path: ./ruleset/TopFreeProxies/globalmedia.yaml
    interval: 86400
  Emby:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Emby/Emby.yaml
    path: ./ruleset/TopFreeProxies/emby.yaml
    interval: 86400
  CnMedia:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia.yaml
    path: ./ruleset/TopFreeProxies/cnmedia.yaml
    interval: 86400
  Private:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/TopFreeProxies/private.txt
    interval: 86400
  Local-LAN:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/LM-Firefly/Rules@master/Clash-RuleSet-Classical/Special/Local-LAN.yaml
    path: ./ruleset/TopFreeProxies/local-lan.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/TopFreeProxies/proxy.txt
    interval: 86400
  Reject:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/TopFreeProxies/reject.txt
    interval: 86400
rules:
  - RULE-SET,Applications,DIRECT
  - IP-CIDR,10.240.0.0/24,DIRECT,no-resolve
  - IP-CIDR,192.168.123.0/24,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - RULE-SET,Local-LAN,DIRECT,no-resolve
  - RULE-SET,Reject,REJECT,no-resolve
  - RULE-SET,Private,DIRECT,no-resolve
  - RULE-SET,Apple,苹果服务
  - RULE-SET,iCloud,苹果服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,CnMedia,国内媒体
  - RULE-SET,Emby,全球媒体
  - RULE-SET,GlobalMedia,全球媒体

  - GEOIP,CN,DIRECT
  - RULE-SET,Proxy,节点选择
  - MATCH,漏网之鱼
